  
  - name: Download JDK
    get_url: url="{{ java.download_repo_base_dir }}/{{ java.download_file_name }}" dest="{{ java_base_dir }}"
 
  - name: Extract JDK
    unarchive: 
      src: "{{ java_base_dir }}/{{ java.download_file_name }}"
      dest: "{{ java_base_dir }}"
      remote_src: true
  
  - name: Set Permision to JAVA folder
    file:
      dest: "{{ java_base_dir }}/{{ java.full_version }}"
      owner: "{{ java_user }}"
      group: "{{ middleware_group }}"
      mode: 0755 
      recurse: yes

  - name: set fact jdk_folder
    set_fact:
      jdk_folder: "{{ java_base_dir }}/{{ java.full_version }}"

  - name: Change entropy device for java
    command: "sed -i.bak 's/\\/dev\\/random/\\/dev\\/.\\/urandom/' {{ jdk_folder }}/jre/lib/security/java.security"

  - name: Add JAVA_HOME environment variariables in bashrc
    lineinfile: dest='/home/{{ java_user }}/.bashrc' line='export JAVA_HOME={{ jdk_folder }}'

  - name: Add Java bin folder to path in bashrc
    lineinfile: dest='/home/{{ java_user }}/.bashrc' line='export PATH=$PATH:$JAVA_HOME/bin'


  - name: Delete JDK archive
    file:
      path: "{{ java_base_dir }}/{{ java.download_file_name }}"
      state: absent





  - name: set internal vars for java version
    set_fact:
      jdk_version_detail: "jdk{{ java.version }}u{{ java.subversion }}"

  - name: set fact JDK installed
    set_fact: 
       "{{ jdk_version_detail }}" : installed


  - name: save template to facts
    template: src=template/result.j2 dest=/tmp/jdk.version owner="{{ java_user }}" group="{{ middleware_group }}" mode=750 
